# Generated by Django 2.2 on 2021-07-01 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='day',
            field=models.CharField(default='five', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='joined',
            field=models.ManyToManyField(related_name='members', to='musicAPP.Users'),
        ),
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Wall_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='musicAPP.Group')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='musicAPP.Users')),
            ],
        ),
    ]
