# Generated by Django 2.2 on 2021-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='likes',
            field=models.ManyToManyField(related_name='like', to='musicAPP.Users'),
        ),
    ]
